# Generated by Django 2.1.15 on 2021-02-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_rate_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='max_order',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='parent',
        ),
    ]
